---
archive:
  back_to_all_dates: « Back to All Dates
  no_results: No results found.
  previous_page: « Previous Page
  next_page: Next Page »

forms:
  comment:
    url_prompt: Add Website URL »

  subscribe:
    follow_link: Follow this Posthaven »
    prompt: |
      <button class="subscribe-button">Subscribe Now</button>
    unfollow_link: Unfollow »

read_more: Read more »

pagination:
  first: ‹ First
  previous: « Previous
  gap: …
  next: Next ›
  last: Last »
